# Generated by Django 3.0.5 on 2020-06-02 10:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=13)),
                ('email', models.EmailField(max_length=150)),
                ('proof', models.FileField(upload_to=core.models.user_directory_path)),
                ('org', models.CharField(choices=[('SELF', 'Self'), ('GROUP', 'Group'), ('CORPORATE', 'Corporate'), ('OTHERS', 'Others')], default='SELF', max_length=20)),
                ('ticket', models.IntegerField(default=1)),
                ('token', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
